branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

jobs:
  include:
    - os: osx
      arch: amd64
      osx_image: xcode12.2
      language: node_js
      node_js: "12"
      env:
        - ELECTRON_CACHE=".cache/electron"
        - ELECTRON_BUILDER_CACHE=".cache/electron-builder"

    - os: linux
      arch: amd64
      env:
        - ELECTRON_CACHE=".cache/electron"
        - ELECTRON_BUILDER_CACHE=".cache/electron-builder"
      services: docker
      language: generic

cache:
  directories:
    - node_modules
    - .cache/electron
    - .cache/electron-builder

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -vE '\r|\n' | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        electronuserland/builder:wine \
        /bin/bash -c "npm install && npm test && npm run dist -- --linux --win"
    else
      npm test && npm run dist
    fi

before_cache:
  - rm -rf .cache/electron-builder/wine

before_deploy:
  - ls -alh dist

deploy:
  on:
    branch: master
  provider: releases
  token: $GH_TOKEN
  file_glob: true
  file:
    - "dist/*.dmg"
    - "dist/*.AppImage"
    - "dist/*.exe"
  cleanup: false
  draft: true
  overwrite: true